### ISSUE TITLE
bash: /usr/libexec/grepconf.sh: No such file or directory

### ISSUE THREAD

**Issue by fgeorgatos** [plabrop/bic#14]
```
[fgeorgatos@node004 ~]$ bash
bash: /usr/libexec/grepconf.sh: No such file or directory
[fgeorgatos@node004 ~]$ grep -R /usr/libexec/grepconf.sh /etc/profile.d
/etc/profile.d/colorgrep.sh:/usr/libexec/grepconf.sh -c || return
/etc/profile.d/colorgrep.csh:/usr/libexec/grepconf.sh -c
[fgeorgatos@node004 ~]$ rpm -qf /etc/profile.d/colorgrep.*sh
file /etc/profile.d/colorgrep.csh is not owned by any package
file /etc/profile.d/colorgrep.sh is not owned by any package
[fgeorgatos@node004 ~]$
```

**Comment by fgeorgatos** [comment]
hm... I'm with the impression that this is half-back-ported configuration of centos7:

```
[fgeorgatos@node003 ~]$ lsb_release -d
Description:    CentOS Linux release 7.2.1511 (Core)
[fgeorgatos@node003 ~]$ rpm -qf /etc/profile.d/colorgrep.sh /usr/libexec/grepconf.sh
grep-2.20-2.el7.x86_64
grep-2.20-2.el7.x86_64
```

**Comment by fgeorgatos** [comment]
ignore, wrong place to report this ;-)

**Comment by rsabir** [comment]
Have you succeeded at finding the source of the problem?

**Comment by fgeorgatos** [comment]
@rsabir : somebody had copied a centos7 script on centos6 and the binary was not available there

**Comment by nanfengnan1** [comment]
@fgeorgatos : hei,brother,i try your method and i don't solve this problem,it promts this problem
[root@localhost home]# source /etc/profile
bash: /usr/libexec/grepconf.sh: No such file or directory

**Comment by nanfengnan1** [comment]
hi,everyone,i wonder what i do,i don't have /usr/libexec.   but the chinese baidu don't tell me the solving method.  the error is:
![image](https://user-images.githubusercontent.com/63905580/190836840-cbd70601-3445-482e-a5ab-6ea7b3338e94.png)
