### ISSUE TITLE
/usr/bin/basename does not exist under rhel6.x (use /bin/basename instead)

### ISSUE THREAD

**Issue by fgeorgatos** [plabrop/bic#39]
The culprit is clear:

```
[root@node002 ~]# su - fgeorgatos
-bash: /usr/bin/basename: No such file or directory
[...]
[fgeorgatos@node002 ~]$ ll /usr/bin/basename
ls: cannot access /usr/bin/basename: No such file or directory
[fgeorgatos@node002 ~]$ which basename
/bin/basename
[fgeorgatos@node002 ~]$ grep usr/bin/basename /etc/profile.d -R
/etc/profile.d/z00_lmod.sh:  my_shell=$(/usr/bin/basename $my_shell)
```

This is the same bug as others have hit: https://www.google.co.uk/search?q=z00_lmod.sh+%2Fusr%2Fbin%2Fps

btw. finding your current shell type is already hard enough in itself...
http://stackoverflow.com/questions/3327013/how-to-determine-the-current-shell-im-working-on

**Comment by fgeorgatos** [comment]
btw. this is no different than https://github.com/TACC/Lmod/issues/118

**Comment by andy5995** [comment]
I seem to recall getting the basename of a file without the 'basename' comand was discussed in [this thread](http://www.linuxquestions.org/questions/programming-9/bash-script-return-full-path-and-filename-680368-print/)

**Comment by fgeorgatos** [comment]
this has been handled by PR #52, closing!
