### ISSUE TITLE
z01-default_modules.sh is buggy, uses -n instead of -z

### ISSUE THREAD

**Issue by fgeorgatos** [plabrop/bic#60]
(see the other scripts for reference)

**Comment by fgeorgatos** [comment]
btw. a more elegant way to handle this is `[[ -z "$USER_IS_ROOT" ]] && return`
(because it leaves the rest of the code below it stable and unindented - it's already complicated as-is.

**Comment by fgeorgatos** [comment]
while you are at it `z00_lmod.csh` is unescaped via `USER_IS_ROOT`. good moment to fix it, too

**Comment by fgeorgatos** [comment]
OK, this has been fixed at least as late in #69, if not earlier.

Observed side-effect: 
* standard rpm upgrade drops change in `z01-default_modules.sh.rpmnew` (undesired, watch out)

**Comment by fgeorgatos** [comment]
eh, I need to reopen this, because `-z` is not the final answer.
Sry about it, this was caused a side-effect of `.rpmsave` (and as such incomplete testing).

**Comment by johnnydevaprasad** [comment]
`z01-default_modules.sh` is `confignoreplace`, so what you are seeing is expected behavior. If you have custom changes you dont want them to be overwritten. This file is not going to change very often, so it is expected that the admin fixes this manually.

**Comment by fgeorgatos** [comment]
Hi @johnnydevaprasad : the `confignoreplace` is correct choice, I just meant it blinded me in detecting the issue and hence, I reported it very late in the process!

**Comment by fgeorgatos** [comment]
this appears to work as intended now, so closing
